services:
  softioc:
    extends:
      file: docker-compose.yml
      service: softioc

  kafka:
    extends:
      file: docker-compose.yml
      service: kafka

  connect:
    extends:
      file: docker-compose.yml
      service: connect
    build:
      context: .
      dockerfile: Dockerfile