services:
  softioc:
    extends:
      file: docker-compose.yml
      service: softioc

  zookeeper:
    extends:
      file: docker-compose.yml
      service: zookeeper

  kafka:
    extends:
      file: docker-compose.yml
      service: kafka

  connect:
    extends:
      file: docker-compose.yml
      service: connect
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_TYPE: local-src