---
version: '2'

services:
  kafka:
    environment:
      CREATE_TOPICS: 'alarms:1:1:compact,active-alarms:1:1:compact,shelved-alarms:1:1:compact'

  registry:
    image: confluentinc/cp-schema-registry:5.5.0
    hostname: registry
    container_name: registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: registry

  console:
    image: slominskir/kafka-alarm-system:0.1.0
    hostname: console
    container_name: console
    depends_on:
      - zookeeper
      - kafka
      - registry
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"
      ALARM_DEFINITIONS: "channel1|channel1|INJ|RF|/|/,channel2|channel2|INJ|RF|/|/,channel3|channel3|INJ|RF|/|/"

  connect:
    environment:
      MONITOR_CHANNELS: "channel1:active-alarm:a,channel2:active-alarm:a,channel3:active-alarm:a"
    volumes:
      - ./examples/connect-config/distributed-alarms:/config
