---
version: '3.9'

services:
  softioc:
    extends:
      file: deps.yml
      service: softioc

  zookeeper:
    extends:
      file: deps.yml
      service: zookeeper

  kafka:
    extends:
      file: deps.yml
      service: kafka

  connect:
    hostname: connect
    container_name: connect
    depends_on:
      - zookeeper
      - kafka
      - softioc
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      #MONITOR_CHANNELS: "/config/channels"
      MONITOR_CHANNELS: "channel1|topic1|v|key1,channel2|topic2|v|key2,channel3|topic3|v|key3"
    volumes:
      - ./examples/connect-config/distributed:/config
