ARG RUN_IMAGE=debezium/connect-base:1.9.2.Final

################## Stage 0
FROM ${RUN_IMAGE} as runner
ARG CUSTOM_CRT_URL
USER root
ENV PATH="/kafka/bin:${PATH}"
RUN if [ -z "${CUSTOM_CRT_URL}" ] ; then echo "No custom cert needed"; else \
       mkdir -p /usr/local/share/ca-certificates \
       && curl -o /usr/local/share/ca-certificates/customcert.crt $CUSTOM_CRT_URL \
       && cat /usr/local/share/ca-certificates/customcert.crt >> /etc/ssl/certs/ca-certificates.crt \
       && keytool -import -alias custom -file /usr/local/share/ca-certificates/customcert.crt -cacerts -storepass changeit -noprompt \
    ; fi \
    && microdnf install -y hostname jq java-11-openjdk-devel vim \
    && microdnf clean all