services:
  softioc:
    extends:
      file: deps.yml
      service: softioc

  kafka:
    extends:
      file: deps.yml
      service: kafka

  connect:
    hostname: connect
    container_name: connect
    depends_on:
      - kafka
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      CONNECT_MAX_REQUEST_SIZE: 5242880
      #MONITOR_CHANNELS: "/config/channels"
      MONITOR_CHANNELS: "channel1|topic1|v|key1,channel2|topic2|v|key2,channel3|topic3|v|key3"
      #CREATE_TOPICS: "topic1:1:1:compact,topic2:1:1:compact,topic3:1:1:compact"
    volumes:
      - ./examples/connect-config/distributed:/config
