---
version: '3.8'

networks:
  cluster:
    name: 'alarm-cluster'

services:
  softioc:
    image: slominskir/softioc:1.1.0
    tty: true
    stdin_open: true
    hostname: softioc
    container_name: softioc
    ports:
      - "5064:5064/tcp"
      - "5065:5065/tcp"
      - "5064:5064/udp"
      - "5065:5065/udp"
    volumes:
      - ../softioc-db:/db
      - ../softioc-scripts:/scripts
    networks:
      - cluster

  registry:
    image: confluentinc/cp-schema-registry:5.5.0
    hostname: registry
    container_name: registry
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-1:9092
      SCHEMA_REGISTRY_HOST_NAME: registry
    networks:
      - cluster

  console:
    image: slominskir/kafka-alarm-system:0.1.0
    hostname: console
    container_name: console
    depends_on:
      - registry
    environment:
      BOOTSTRAP_SERVERS: "kafka-1:9092"
      SCHEMA_REGISTRY: "http://registry:8081"
      ALARM_DEFINITIONS: "channel1|channel1|INJ|RF|/|/,channel2|channel2|INJ|RF|/|/,channel3|channel3|INJ|RF|/|/"
    networks:
      - cluster