---
version: '3.8'

networks:
  cluster:
    name: 'alarm-cluster'

services:
  connect-1:
    image: slominskir/epics2kafka:0.5.0
    hostname: connect-1
    container_name: connect-1
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      MONITOR_CHANNELS: "/config/channels"
    volumes:
      - ../connect-config/distributed-alarms-cluster:/config
    networks:
      - cluster

  connect-2:
    image: slominskir/epics2kafka:0.5.0
    hostname: connect-2
    container_name: connect-2
    ports:
      - 8002:8083
    environment:
      BOOTSTRAP_SERVERS: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
    entrypoint: ["/docker-entrypoint.sh", "start"]
    networks:
      - cluster

  connect-3:
    image: slominskir/epics2kafka:0.5.0
    hostname: connect-3
    container_name: connect-3
    ports:
      - 8003:8083
    environment:
      BOOTSTRAP_SERVERS: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
    entrypoint: ["/docker-entrypoint.sh", "start"]
    networks:
      - cluster