---
version: '3.8'

networks:
  cluster:
    name: 'alarm-cluster'

services:
  zookeeper-1:
    image: debezium/zookeeper:1.3
    hostname: zookeeper-1
    container_name: zookeeper-1
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      SERVER_ID: '1'
      SERVER_COUNT: '3'
    networks:
      - cluster

  zookeeper-2:
    image: debezium/zookeeper:1.3
    hostname: zookeeper-2
    container_name: zookeeper-2
    ports:
      - "2102:2181"
      - "2802:2888"
      - "3802:3888"
    environment:
      SERVER_ID: '2'
      SERVER_COUNT: '3'
    networks:
      - cluster

  zookeeper-3:
    image: debezium/zookeeper:1.3
    hostname: zookeeper-3
    container_name: zookeeper-3
    ports:
      - "2103:2181"
      - "2803:2888"
      - "3803:3888"
    environment:
      SERVER_ID: '3'
      SERVER_COUNT: '3'
    networks:
      - cluster
