name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      - name: Start containers
        run: docker compose -f "build.yml" up -d
      - name: Wait for containers to settle
        run: docker exec -i connect bash -c "sleep 20"
      - name: Run integration test
        run: ./gradlew integrationTest
      - name: Dump connect logs
        if: always()
        run: docker logs connect
      - name: Stop containers
        if: always()
        run: docker compose -f "build.yml" down
