name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Start containers
        run: docker compose -f "test.yml" up -d
      - name: Wait for containers to settle
        run: docker exec -i connect bash -c "sleep 20"
      - name: Run integration test
        run: docker exec -i tester sh -c "cd /app; gradle integrationTest"
      - name: Dump connect logs
        if: always()
        run: docker logs connect
      - name: Dump tester logs
        if: always()
        run: docker logs tester
      - name: Stop containers
        if: always()
        run: docker compose -f "test.yml" down
